---
deployment:
    tasks:
        - export DEPLOYPATH=/home/alicqplp/moviefax.alicecutler.dev/
        - /bin/cp -R backend $DEPLOYPATH
        - /bin/cp -R frontend $DEPLOYPATH
        - /bin/cp package.json $DEPLOYPATH
